#:kivy 1.0

<clickyclack>:
    font_size: 24
    text: 'clicky'
    on_press: self.toggle()
<clackyclick>:
    font_size: 24
    text: 'clacky'
    on_press: self.toggle()
<numbox>:
    orientation: 'vertical'
    Label:
        font_size: 24
        text: 'Your score is ' + str(root.count)
    Label:
        font_size: 20
        text: 'you have ' + str(root.time) + ' seconds to get the best score possible'
    clickyclack:
    clackyclick:
